wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1727635417
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      - 61
      4: 3.11.5
      5: 0.17.8
      8:
      - 1
      - 5
      13: linux-x86_64
